spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver
  thymeleaf:
    cache: false
    check-template-location: false
    mode: HTML5
    encoding: utf-8
    content-type: text/html
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect